# Generated by Django 4.1.7 on 2023-03-30 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculadora", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Partidas_Jugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("minutos_jugados", models.IntegerField()),
                ("puntaje", models.IntegerField()),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculadora.usuarios",
                    ),
                ),
            ],
        ),
    ]
