# Generated by Django 4.1.7 on 2023-03-31 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculadora",
            "0004_partida_jugadores_usuarios_delete_partidas_jugador_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PartidaJugador",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("minutos_jugados", models.PositiveIntegerField()),
                ("puntaje", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Partida_Jugadores",
        ),
        migrations.DeleteModel(
            name="usuarios",
        ),
        migrations.AddField(
            model_name="partidajugador",
            name="id_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="calculadora.usuario"
            ),
        ),
    ]
