# Generated by Django 4.1.7 on 2023-04-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculadora",
            "0005_partidajugador_usuario_delete_partida_jugadores_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("minutos_jugados", models.IntegerField()),
                ("puntaje", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="usuario",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="PartidaJugador",
        ),
        migrations.AddField(
            model_name="partida",
            name="id_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="calculadora.usuario"
            ),
        ),
    ]
